#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  TERRAFORM_VERSION="${1:-${TERRAFORM_VERSION:-}}"

  local url_terraform_Darwin="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_darwin_amd64.zip"
  local url_terraform_Linux="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

  local url_terraform="url_terraform_$(uname -s)"
  local fnm_terraform="$(basename "${!url_terraform}")"
  cache curl "$fnm_terraform" "${!url_terraform}"

  pushd bin
  unzip -o "${BASEBOX_CACHE}/curl/$fnm_terraform"
  chmod 755 terraform
  popd
}

main "$@"
