#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local url_terraform_Darwin='https://releases.hashicorp.com/terraform/0.6.14/terraform_0.6.14_darwin_amd64.zip'
  local url_terraform_Linux='https://releases.hashicorp.com/terraform/0.6.14/terraform_0.6.14_linux_amd64.zip'

  local url_terraform="url_terraform_$(uname -s)"
  local fnm_terraform="$(basename "${!url_terraform}")"
  cache curl "$fnm_terraform" "${!url_terraform}"

  pushd bin
  unzip -o "${BASEBOX_CACHE}/curl/$fnm_terraform"
  (set +f; chmod 755 terraform terraform-*)
  popd
}

bootstrap
