#!/usr/bin/env bash

function _terraform_profile {
  local shome="${_terraform_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  TERRAFORM_VERSION="0.7.12"
}

_terraform_profile
