#!/usr/bin/env bash

function main {
  local shome="${_terraform_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$(type -P terraform)" ]]; then
    return 1
  else
    return 0
  fi
}

source sub "$0" "$@"
