#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  local ver_terraform_landscape="$(landscape --version 2>/dev/null | awk '{print $3}' || true)"
  jq -n \
    --arg terraform_landscape "$ver_terraform_landscape" \
    '{terraform_landscape: $terraform_landscape}'
}

version "$@"
