#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_terraform="$(terraform --version 2>&- | awk '{print $2}' | perl -pe 's{^v}{}' || true)"
  jq -n --arg terraform "$ver_terraform" '{terraform: $terraform}'
}

version "$@"
