#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  local ver_terraform_landscape="$(landscape --version 2>/dev/null | awk '{print $3}' || true)"
  local ver_terraform_docs="$(terraform-docs --version 2>/dev/null | sed 's#^v##' || true)"
  jq -n \
    --arg terraform_landscape "$ver_terraform_landscape" \
    --arg terraform_docs "$ver_terraform_docs" \
    '{terraform_landscape: $terraform_landscape, terraform_docs: $terraform_docs}'
}

version "$@"
